# Generated by Django 3.0.3 on 2020-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='trade_info',
            field=models.ManyToManyField(related_name='trade_info_set', through='room.TradeInfo', to='room.TradeType'),
        ),
        migrations.AlterModelTable(
            name='tradeinfo',
            table='trade_infos',
        ),
    ]
