# Generated by Django 3.0.3 on 2020-03-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeinfo',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
